## Build phase

FROM node:22.11 as build

WORKDIR /app

# Copy package files and install dependencies
COPY ./package.json ./package-lock.json ./
RUN npm install

# Copy remaining application files
COPY . .


RUN npm run build

## Serve phase
FROM nginx:1.27.2

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
