include:
  - ./docker-compose.yml

services:
  seed_test_data:
    build:
      context: ./seed-test-data
      dockerfile: Dockerfile
    container_name: seed_test_data
    image: seed_test_data
    restart: "no"
    environment:
      - API_BASE_URL=http://api:8080
    networks:
      - api-network
    depends_on:
      api:
        condition: service_healthy

  cypress:
    build:
      context: ./end-to-end-tests
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "pgrep", "cypress"]
      interval: 10s
      timeout: 5s
      retries: 3
    container_name: cypress
    image: cypress
    depends_on:
      - seed_test_data
      - frontend
    environment:
      - CYPRESS_BASE_URL=http://frontend:3000
#    volumes:
#      - ./cypress:/e2e
#    working_dir: /e2e
#    command: npx cypress run
    networks:
      - test-network
